web:
  image: ngnix:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./code:/code
    - ./nginx.conf:/etc/ngnix/conf.d/default.conf

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
